"""
SQLAlchemy ORM models for PostgreSQL database.
Defines the database schema with proper relationships.
"""
from sqlalchemy import Column, Integer, String, Text, JSON, DateTime, ForeignKey, Boolean
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database.connection import Base


class Quiz(Base):
    """
    Main quiz table storing Wikipedia article information and metadata.
    """
    __tablename__ = "quizzes"
    
    id = Column(Integer, primary_key=True, index=True)
    url = Column(String(500), unique=True, nullable=False, index=True)  # Wikipedia URL
    title = Column(String(300), nullable=False)  # Article title
    summary = Column(Text, nullable=True)  # Article summary
    key_entities = Column(JSON, nullable=True)  # {people: [], organizations: [], locations: []}
    sections = Column(JSON, nullable=True)  # List of section titles
    raw_html = Column(Text, nullable=True)  # BONUS: Store raw HTML
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    # Relationships
    questions = relationship("QuizQuestion", back_populates="quiz", cascade="all, delete-orphan")
    related_topics = relationship("RelatedTopic", back_populates="quiz", cascade="all, delete-orphan")


class QuizQuestion(Base):
    """
    Quiz questions generated by LLM.
    Each question belongs to one quiz.
    """
    __tablename__ = "quiz_questions"
    
    id = Column(Integer, primary_key=True, index=True)
    quiz_id = Column(Integer, ForeignKey("quizzes.id", ondelete="CASCADE"), nullable=False)
    question = Column(Text, nullable=False)
    options = Column(JSON, nullable=False)  # List of 4 options [A, B, C, D]
    answer = Column(String(300), nullable=False)  # Correct answer
    difficulty = Column(String(20), nullable=False)  # easy, medium, hard
    explanation = Column(Text, nullable=True)
    section_reference = Column(String(300), nullable=True)  # BONUS: Section grouping
    
    # Relationship
    quiz = relationship("Quiz", back_populates="questions")


class RelatedTopic(Base):
    """
    Related Wikipedia topics suggested by LLM.
    """
    __tablename__ = "related_topics"
    
    id = Column(Integer, primary_key=True, index=True)
    quiz_id = Column(Integer, ForeignKey("quizzes.id", ondelete="CASCADE"), nullable=False)
    topic = Column(String(200), nullable=False)
    
    # Relationship
    quiz = relationship("Quiz", back_populates="related_topics")


# Create all tables
def init_db():
    """
    Initialize database tables.
    Call this when starting the application.
    """
    from app.database.connection import engine
    Base.metadata.create_all(bind=engine)
